### ISSUE TITLE
submodule 2018 的內容更新後自動 update

### ISSUE THREAD

**Issue by choznerol** [g0v/summit.g0v.tw#2]
目前都是 2018 repo 更新後再來手動更新這邊實在有點冗，稍微找了一下也沒發現什麼很直接的解法，因為 github 似乎也沒有偵測 submodule 更新的 API ，所以可能只能在 2018 裡串 webhook 處理（像 [這篇](https://stackoverflow.com/questions/34707506/how-can-a-commit-in-git-submodule-trigger-a-build-in-continuous-integration) 的一樓）

@denny0223 大大之前有相關經驗嗎？

**Comment by choznerol** [comment]
或是簡單一點開個cron job一天跑一次 git submodule update 應該也行，但需要 @denny0223  幫開travis 權限

**Comment by denny0223** [comment]
已經有把相關的 team 權限加入本專案

**Comment by choznerol** [comment]
![image](https://user-images.githubusercontent.com/12410942/37713722-c012461e-2d52-11e8-9a20-2e97a9d5bc3c.png)

**Comment by choznerol** [comment]
會不會是需要到collaborator或admin的權限？
