### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by choznerol** [g0v/summit.g0v.tw#5]
@zbryikt 不確定要問誰XD 這個之後會有計畫要加嗎？

**Comment by othree** [comment]
GitHub pages 還沒正式支援 custom domain 的 HTTPS
我剛剛看 summit.g0v.tw 已經支援了（有被申請 lets encrypt、而且可以開）
但是打開後會爛掉，common name 不對的錯誤，所以我又先關回去

**Comment by ronnywang** [comment]
最省事就是直接過 cloudflare 吧 xD

**Comment by denny0223** [comment]
最省事就是上 CDN
sitcon.org 也是放在 gh-pages 前面有過 CloudFront

**Comment by othree** [comment]
支援了，看要不要開 enforce 強制 https 而已
首頁的 redirect 可能也要修一下

**Comment by choznerol** [comment]
@othree 首頁的 redirect 是指這個嗎
https://github.com/g0v/summit.g0v.tw/blob/gh-pages/index.html#L6
感覺應該不影響（？
