### ISSUE TITLE
2018 議程表可以放分軌標題嗎？

### ISSUE THREAD

**Issue by pm5** [g0v/summit.g0v.tw#7]
https://summit.g0v.tw/2018/agenda/

10/6-7 的議程有分軌，每一軌 3 個演講與一個提問與對話。可以放上標題的話，會眾會比較好理解這一軌在講什麼。

**Comment by choznerol** [comment]
已經開需求給設計師囉，如果有呈現方式上的其他建議可以在[InVision](https://invis.io/3VMJFRNTYXG#/308786949_g0v_-2-)討論喔

**Comment by choznerol** [comment]
設計那邊趕工完成了，應該這兩天會先上 [session分類](https://github.com/g0v/summit2018/issues/105#issuecomment-418122806) ，分軌我再看看週四前有沒有機會

**Comment by choznerol** [comment]
分軌已經上了歐，在議程頁選 Oct 6 裡會有，但如果進到網站有遇到「需要 refresh 一次才看得見更新」的狀況麻煩留言跟我說一下
